### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/ompi-release-bot#1]
This is a dummy issue to test the bot

**Comment by ompiteam** [comment]
Hello, dummy issue!

assign:@ggouaillardet

**Comment by jsquyres** [comment]
Oh, right -- duh -- need to wait for @ggouaillardet to assign the secret so that it has rights to do stuff to issues...

**Comment by ggouaillardet** [comment]
assign:@jsquyres

**Comment by jsquyres** [comment]
assign:@ggouaillardet

**Comment by jsquyres** [comment]
unassign:

**Comment by jsquyres** [comment]
assign:jsquyres

**Comment by jsquyres** [comment]
assign:this-user-does-not-exist

**Comment by jsquyres** [comment]
label:bug
assign:@jsquyres
milestone:v0.1

**Comment by jsquyres** [comment]
label:conditional approval

**Comment by jsquyres** [comment]
label:this-label-does-not-exist

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
label:reviewed

**Comment by jsquyres** [comment]
nolabel:reviewed

**Comment by jsquyres** [comment]
labelno:reviewed

**Comment by jsquyres** [comment]
milestone:v1.0

**Comment by jsquyres** [comment]
milestone:v3.8

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
labelno:bug

**Comment by jsquyres** [comment]
label:enhancement

**Comment by ggouaillardet** [comment]
labelno:bug

**Comment by jsquyres** [comment]
label:enhancement
:+1:

**Comment by jsquyres** [comment]
@ggouaillardet I just added support for :-1: and "nolabel" (vs. "labelno").  Can you update the bot?  I'm afraid to do it again to break something on your back-end.  :-)

**Comment by ggouaillardet** [comment]
:-1

**Comment by ggouaillardet** [comment]
:-1:

**Comment by ggouaillardet** [comment]
@jsquyres 

done　！

backend always worked for me, maybe an intermittent issue...

**Comment by jsquyres** [comment]
Nice!

Per the email, I sent to you, I'm thinking:
1. Let's just remove spaces in the labels.
2. I think "nolabel" is better. Is there a reason for "labelno"?
3. Can you frob the script to accept "assign:<SPACE>@foo"?

**Comment by jsquyres** [comment]
Per last comment from the ompibot... LOL!!  :-)

**Comment by ggouaillardet** [comment]
@jsquyres will do

labelno is an old hack ...
at that time, nolabel:enhancement was matched by the find_label and find_nolabel regexps, so i used labelno as a trick to get only one match

about assigning a request to someone, here are the lists of assignees (directly from the github api)
https://api.github.com/repos/open-mpi/ompi-release-bot/assignees
means the bot can assign request to 4 users only (e.g. i cannot assign an issue to Ralph !)

but

https://api.github.com/repos/open-mpi/ompi-release/assignees
means the bot is very likely able to assign an issue/pr to any ompi developer :-)

this is likely linked to the config of the repository though i have no way to test it
(and if it just works, i am fine if i do not master this part ...)

**Comment by ggouaillardet** [comment]
assign: @ggouaillardet

**Comment by ggouaillardet** [comment]
assign: @rhc54

**Comment by ggouaillardet** [comment]
unassign:

**Comment by ggouaillardet** [comment]
assign: @ggouaillardet

**Comment by ggouaillardet** [comment]
unassign:

**Comment by ggouaillardet** [comment]
assign: @rhc54

**Comment by ggouaillardet** [comment]
assign: @rhc54

**Comment by ggouaillardet** [comment]
assign: @rhc54

**Comment by jsquyres** [comment]
FWIW: Your comments about only being able to assign to users who can read or write to the repo sounds fine to me.

**Comment by jsquyres** [comment]
assign: @ggouaillardet

**Comment by jsquyres** [comment]
assign:@jsquyres

**Comment by ggouaillardet** [comment]
assign: @ggouaillardet

**Comment by jsquyres** [comment]
assign:bogus-user

**Comment by jsquyres** [comment]
label:bogus-label

**Comment by jsquyres** [comment]
label:bug
label:enhancement
label:bogus-label

**Comment by jsquyres** [comment]
label:code-cleanup-low-pri
