### ISSUE TITLE
Only allow org members to send bot actions

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/ompi-release-bot#2]
I mentioned this script on the weekly OMPI webex today.

Dave G. brought up a good point: we should restrict the list of users who are allowed to issue bot commands to be those who are in the Open MPI organization.

I.e., anyone who is a member of the open-mpi Github org can issue "label:..." and friends commands.  Anyone who creates an issue/PR or adds a comment who is not in the org cannot issue "label:..." (etc.) commands.  Indeed, we might want to have the bot add a comment about "Label [foo] not added because [user] is not a member of the organization", just so that they can know that their commands were not processed.

@ggouaillardet Can you add this whitelisting functionality?

**Comment by jsquyres** [comment]
assign: @ggouaillardet

**Comment by ggouaillardet** [comment]
Done in open-mpi/ompi-release-bot@78f0dc9d2225ad7728be16ba102819355b447d37
